### ISSUE TITLE
Carry binding through multiple examples

### ISSUE THREAD

**Issue by tfausak** [tfausak/erudite#3]
Variables and functions defined in an example aren't available in the next example. For instance:

``` irb
>> x = 1
=> 1
>> x
=> 1
```

```
- PASS
- FAIL
  Source: x
  Expected:
    Output: nil
    Result: "1"
  Actual:
    Output: "NameError: undefined local variable or method `x' for main:Object\n"
    Result: "nil"
```
